name: Deploy to Fly.io

on:
  push:
    branches:
      - main # Troque para sua branch se não for "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flyctl
        uses: superfly/flyctl-action@v1
        with:
          token: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
