name: Deploy to Fly.io

on:
  push:
    branches:
      - main    # ou outra branch que você queira automatizar o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Fly.io
        uses: superfly/flyctl-action@v1
        with:
          token: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        uses: superfly/flyctl-action@v1
        with:
          args: deploy --config fly.toml --verbose
